'use strict';

window.FCO_AGENCIES = [
  {
    "prefixo": "0014",
    "nome": "CORUMBA",
    "nomeCompleto": "Agência 0014 - CORUMBA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Treze de Junho, 914",
    "bairro": "Centro",
    "municipio": "Corumba",
    "uf": "MS",
    "cep": "79.300-040"
  },
  {
    "prefixo": "0048",
    "nome": "AFONSO PENA",
    "nomeCompleto": "Agência 0048 - AFONSO PENA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Afonso Pena, 2202",
    "bairro": "Centro",
    "municipio": "Campo Grande",
    "uf": "MS",
    "cep": "79.002-908"
  },
  {
    "prefixo": "0078",
    "nome": "PONTA PORA",
    "nomeCompleto": "Agência 0078 - PONTA PORA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Brasil, 2623",
    "bairro": "Centro",
    "municipio": "Ponta Pora",
    "uf": "MS",
    "cep": "79.904-672"
  },
  {
    "prefixo": "0123",
    "nome": "AQUIDAUANA",
    "nomeCompleto": "Agência 0123 - AQUIDAUANA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Manoel A. Paes de Barros, 535",
    "bairro": "Centro",
    "municipio": "Aquidauana",
    "uf": "MS",
    "cep": "79.200-000"
  },
  {
    "prefixo": "0208",
    "nome": "TRES LAGOAS",
    "nomeCompleto": "Agência 0208 - TRES LAGOAS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Paranaiba, 598",
    "bairro": "Centro",
    "municipio": "Tres Lagoas",
    "uf": "MS",
    "cep": "79.601-050"
  },
  {
    "prefixo": "0211",
    "nome": "MARACAJU",
    "nomeCompleto": "Agência 0211 - MARACAJU",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Melanio Garcia Barbosa, 361",
    "bairro": "Centro",
    "municipio": "Maracaju",
    "uf": "MS",
    "cep": "79.150-000"
  },
  {
    "prefixo": "0267",
    "nome": "BELA VISTA-MS",
    "nomeCompleto": "Agência 0267 - BELA VISTA-MS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Guia Lopes, 917",
    "bairro": "Centro",
    "municipio": "Bela Vista",
    "uf": "MS",
    "cep": "79.260-000"
  },
  {
    "prefixo": "0391",
    "nome": "DOURADOS",
    "nomeCompleto": "Agência 0391 - DOURADOS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Joaquim Teixeira Alves, 1796",
    "bairro": "Centro",
    "municipio": "Dourados",
    "uf": "MS",
    "cep": "79.801-015"
  },
  {
    "prefixo": "0484",
    "nome": "PARANAIBA",
    "nomeCompleto": "Agência 0484 - PARANAIBA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Wladislau Garcia Gomes, 1200",
    "bairro": "Centro",
    "municipio": "Paranaiba",
    "uf": "MS",
    "cep": "79.500-000"
  },
  {
    "prefixo": "0543",
    "nome": "GUIA LOPES DA LAGUNA",
    "nomeCompleto": "Agência 0543 - GUIA LOPES DA LAGUNA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Visconde de Taunay, 608",
    "bairro": "Centro",
    "municipio": "Guia Lopes Da Laguna",
    "uf": "MS",
    "cep": "79.230-000"
  },
  {
    "prefixo": "0552",
    "nome": "COXIM",
    "nomeCompleto": "Agência 0552 - COXIM",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Antonio de Albuquerque, 248",
    "bairro": "Centro",
    "municipio": "Coxim",
    "uf": "MS",
    "cep": "79.400-000"
  },
  {
    "prefixo": "0623",
    "nome": "MIRANDA",
    "nomeCompleto": "Agência 0623 - MIRANDA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Tiradentes, 364",
    "bairro": "Centro",
    "municipio": "Miranda",
    "uf": "MS",
    "cep": "79.380-000"
  },
  {
    "prefixo": "0706",
    "nome": "APARECIDA DO TABOADO",
    "nomeCompleto": "Agência 0706 - APARECIDA DO TABOADO",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Presidente Dutra, 4022",
    "bairro": "Centro",
    "municipio": "Aparecida Do Taboado",
    "uf": "MS",
    "cep": "79.570-000"
  },
  {
    "prefixo": "0728",
    "nome": "NOVA ANDRADINA",
    "nomeCompleto": "Agência 0728 - NOVA ANDRADINA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Antonio Joaquim de Moura Andrade, 1400",
    "bairro": "Centro",
    "municipio": "Nova Andradina",
    "uf": "MS",
    "cep": "79.750-910"
  },
  {
    "prefixo": "0740",
    "nome": "RIO BRILHANTE",
    "nomeCompleto": "Agência 0740 - RIO BRILHANTE",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Prefeito Eito Athayde Nogueira, 911",
    "bairro": "Centro",
    "municipio": "Rio Brilhante",
    "uf": "MS",
    "cep": "79.130-000"
  },
  {
    "prefixo": "0742",
    "nome": "PORTO MURTINHO",
    "nomeCompleto": "Agência 0742 - PORTO MURTINHO",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Praça Thomaz Laranjeiras, 34",
    "bairro": "Centro",
    "municipio": "Porto Murtinho",
    "uf": "MS",
    "cep": "79.280-000"
  },
  {
    "prefixo": "0743",
    "nome": "AMAMBAI",
    "nomeCompleto": "Agência 0743 - AMAMBAI",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Tiradentes, 1010",
    "bairro": "Centro",
    "municipio": "Amambai",
    "uf": "MS",
    "cep": "79.990-057"
  },
  {
    "prefixo": "0753",
    "nome": "RIO VERDE M.GROSSO",
    "nomeCompleto": "Agência 0753 - RIO VERDE M.GROSSO",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Barao do Rio Branco, 173",
    "bairro": "Centro",
    "municipio": "Rio Verde De Mato Grosso",
    "uf": "MS",
    "cep": "79.480-000"
  },
  {
    "prefixo": "0793",
    "nome": "GLORIA DE DOURADOS",
    "nomeCompleto": "Agência 0793 - GLORIA DE DOURADOS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Presidente Vargas, 1333",
    "bairro": "Centro",
    "municipio": "Gloria De Dourados",
    "uf": "MS",
    "cep": "79.730-000"
  },
  {
    "prefixo": "0838",
    "nome": "CAMAPUA",
    "nomeCompleto": "Agência 0838 - CAMAPUA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Campo Grande, 255",
    "bairro": "Centro",
    "municipio": "Camapua",
    "uf": "MS",
    "cep": "79.420-000"
  },
  {
    "prefixo": "0845",
    "nome": "FATIMA DO SUL",
    "nomeCompleto": "Agência 0845 - FATIMA DO SUL",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Nove de Julho, 829",
    "bairro": "Centro",
    "municipio": "Fatima Do Sul",
    "uf": "MS",
    "cep": "79.700-000"
  },
  {
    "prefixo": "0897",
    "nome": "BATAGUASSU",
    "nomeCompleto": "Agência 0897 - BATAGUASSU",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Aquidauana, 592",
    "bairro": "Centro",
    "municipio": "Bataguassu",
    "uf": "MS",
    "cep": "79.780-000"
  },
  {
    "prefixo": "0903",
    "nome": "CAARAPO",
    "nomeCompleto": "Agência 0903 - CAARAPO",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Duque de Caxias, 493",
    "bairro": "Centro",
    "municipio": "Caarapo",
    "uf": "MS",
    "cep": "79.940-000"
  },
  {
    "prefixo": "0909",
    "nome": "CASSILANDIA",
    "nomeCompleto": "Agência 0909 - CASSILANDIA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Joaquim Balduino Souza, 596",
    "bairro": "Centro",
    "municipio": "Cassilandia",
    "uf": "MS",
    "cep": "79.540-000"
  },
  {
    "prefixo": "0954",
    "nome": "NAVIRAI",
    "nomeCompleto": "Agência 0954 - NAVIRAI",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Praça Prefeito Euclides A. Fabris, 151",
    "bairro": "Centro",
    "municipio": "Navirai",
    "uf": "MS",
    "cep": "79.950-000"
  },
  {
    "prefixo": "1002",
    "nome": "MUNDO NOVO-MS",
    "nomeCompleto": "Agência 1002 - MUNDO NOVO-MS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Voluntarios da Patria, 90",
    "bairro": "Centro",
    "municipio": "Mundo Novo",
    "uf": "MS",
    "cep": "79.980-000"
  },
  {
    "prefixo": "1031",
    "nome": "BONITO-MS",
    "nomeCompleto": "Agência 1031 - BONITO-MS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Luiz da Costa Leite, 2279",
    "bairro": "Centro",
    "municipio": "Bonito",
    "uf": "MS",
    "cep": "79.290-000"
  },
  {
    "prefixo": "1147",
    "nome": "SIDROLANDIA",
    "nomeCompleto": "Agência 1147 - SIDROLANDIA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Rio Grande do Norte, 160",
    "bairro": "Centro",
    "municipio": "Sidrolandia",
    "uf": "MS",
    "cep": "79.170-000"
  },
  {
    "prefixo": "1324",
    "nome": "ARAL MOREIRA",
    "nomeCompleto": "Agência 1324 - ARAL MOREIRA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Primeiro de Maio, 536",
    "bairro": "Centro",
    "municipio": "Aral Moreira",
    "uf": "MS",
    "cep": "79.930-000"
  },
  {
    "prefixo": "1661",
    "nome": "BRASILANDIA",
    "nomeCompleto": "Agência 1661 - BRASILANDIA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Geronimo Caetano Barbosa, 1074",
    "bairro": "Centro",
    "municipio": "Brasilandia",
    "uf": "MS",
    "cep": "79.670-000"
  },
  {
    "prefixo": "1872",
    "nome": "COSTA RICA",
    "nomeCompleto": "Agência 1872 - COSTA RICA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Jose Ferreira da Costa, 1480",
    "bairro": "Centro",
    "municipio": "Costa Rica",
    "uf": "MS",
    "cep": "79.550-000"
  },
  {
    "prefixo": "1873",
    "nome": "CIDADE MORENA",
    "nomeCompleto": "Agência 1873 - CIDADE MORENA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Joao Pedro de Souza, 1275",
    "bairro": "V.Sta.Doroteia",
    "municipio": "Campo Grande",
    "uf": "MS",
    "cep": "79.004-680"
  },
  {
    "prefixo": "2071",
    "nome": "JARDIM-MS",
    "nomeCompleto": "Agência 2071 - JARDIM-MS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Primeiro de Maio, 608",
    "bairro": "Centro",
    "municipio": "Jardim",
    "uf": "MS",
    "cep": "79.240-000"
  },
  {
    "prefixo": "2175",
    "nome": "ITAPORA",
    "nomeCompleto": "Agência 2175 - ITAPORA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Duque de Caxias, 790",
    "bairro": "Centro",
    "municipio": "Itapora",
    "uf": "MS",
    "cep": "79.890-003"
  },
  {
    "prefixo": "2188",
    "nome": "IVINHEMA",
    "nomeCompleto": "Agência 2188 - IVINHEMA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Brasil, 390",
    "bairro": "Centro",
    "municipio": "Ivinhema",
    "uf": "MS",
    "cep": "79.740-000"
  },
  {
    "prefixo": "2340",
    "nome": "NIOAQUE",
    "nomeCompleto": "Agência 2340 - NIOAQUE",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Benjamin Constant, 342",
    "bairro": "Centro",
    "municipio": "Nioaque",
    "uf": "MS",
    "cep": "79.220-000"
  },
  {
    "prefixo": "2431",
    "nome": "PEDRO GOMES",
    "nomeCompleto": "Agência 2431 - PEDRO GOMES",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Bahia, 545",
    "bairro": "Centro",
    "municipio": "Pedro Gomes",
    "uf": "MS",
    "cep": "79.410-000"
  },
  {
    "prefixo": "2620",
    "nome": "SAO GABRIEL DO OESTE",
    "nomeCompleto": "Agência 2620 - SAO GABRIEL DO OESTE",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Minas Gerais, 1305",
    "bairro": "Centro",
    "municipio": "Sao Gabriel Do Oeste",
    "uf": "MS",
    "cep": "79.490-000"
  },
  {
    "prefixo": "2687",
    "nome": "SETE QUEDAS",
    "nomeCompleto": "Agência 2687 - SETE QUEDAS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Monteiro Lobato, 333",
    "bairro": "Centro",
    "municipio": "Sete Quedas",
    "uf": "MS",
    "cep": "79.935-000"
  },
  {
    "prefixo": "2848",
    "nome": "BATAYPORA",
    "nomeCompleto": "Agência 2848 - BATAYPORA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Brasil, 1175",
    "bairro": "Centro",
    "municipio": "Bataypora",
    "uf": "MS",
    "cep": "79.760-000"
  },
  {
    "prefixo": "2916",
    "nome": "VIVENDAS",
    "nomeCompleto": "Agência 2916 - VIVENDAS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Afonso Pena, 5572",
    "bairro": "Ch Cachoeira",
    "municipio": "Campo Grande",
    "uf": "MS",
    "cep": "79.040-010"
  },
  {
    "prefixo": "2951",
    "nome": "AVENIDA BANDEIRANTES",
    "nomeCompleto": "Agência 2951 - AVENIDA BANDEIRANTES",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Argemiro Fialho, 54",
    "bairro": "Vl Bandeirante",
    "municipio": "Campo Grande",
    "uf": "MS",
    "cep": "79.006-540"
  },
  {
    "prefixo": "2959",
    "nome": "AV.CORONEL ANTONINO",
    "nomeCompleto": "Agência 2959 - AV.CORONEL ANTONINO",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Coronel Antonino, 194",
    "bairro": "Cel.Antonino",
    "municipio": "Campo Grande",
    "uf": "MS",
    "cep": "79.022-000"
  },
  {
    "prefixo": "3066",
    "nome": "CHAPADAO DO SUL",
    "nomeCompleto": "Agência 3066 - CHAPADAO DO SUL",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Onze, 350",
    "bairro": "Centro",
    "municipio": "Chapadao Do Sul",
    "uf": "MS",
    "cep": "79.560-000"
  },
  {
    "prefixo": "3187",
    "nome": "LAGUNA CARAPA",
    "nomeCompleto": "Agência 3187 - LAGUNA CARAPA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Margarino Alves Brandao, 551",
    "bairro": "Centro",
    "municipio": "Laguna Carapa",
    "uf": "MS",
    "cep": "79.920-000"
  },
  {
    "prefixo": "3426",
    "nome": "PARQUE DOS IPES",
    "nomeCompleto": "Agência 3426 - PARQUE DOS IPES",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Presidente Vargas, 1590",
    "bairro": "Vl Progresso",
    "municipio": "Dourados",
    "uf": "MS",
    "cep": "79.825-090"
  },
  {
    "prefixo": "3496",
    "nome": "JARDIM DOS ESTADOS",
    "nomeCompleto": "Agência 3496 - JARDIM DOS ESTADOS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Maracaju, 1564",
    "bairro": "Centro",
    "municipio": "Campo Grande",
    "uf": "MS",
    "cep": "79.002-212"
  },
  {
    "prefixo": "3497",
    "nome": "JULIO DE CASTILHOS",
    "nomeCompleto": "Agência 3497 - JULIO DE CASTILHOS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Julio de Castilho, 1076",
    "bairro": "L Trabalhador",
    "municipio": "Campo Grande",
    "uf": "MS",
    "cep": "79.112-000"
  },
  {
    "prefixo": "3723",
    "nome": "DOURADINA",
    "nomeCompleto": "Agência 3723 - DOURADINA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Presidente Dutra, 110",
    "bairro": "Centro",
    "municipio": "Douradina",
    "uf": "MS",
    "cep": "79.880-000"
  },
  {
    "prefixo": "3928",
    "nome": "ANAURILANDIA",
    "nomeCompleto": "Agência 3928 - ANAURILANDIA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Mato Grosso, 445",
    "bairro": "Centro",
    "municipio": "Anaurilandia",
    "uf": "MS",
    "cep": "79.770-000"
  },
  {
    "prefixo": "3929",
    "nome": "BANDEIRANTES",
    "nomeCompleto": "Agência 3929 - BANDEIRANTES",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Doutora Jacira Onorio Lyrio, 1340",
    "bairro": "Centro",
    "municipio": "Bandeirantes",
    "uf": "MS",
    "cep": "79.430-000"
  },
  {
    "prefixo": "3933",
    "nome": "ITAQUIRAI",
    "nomeCompleto": "Agência 3933 - ITAQUIRAI",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Treze de Maio, 393",
    "bairro": "Centro",
    "municipio": "Itaquirai",
    "uf": "MS",
    "cep": "79.965-000"
  },
  {
    "prefixo": "3937",
    "nome": "SONORA",
    "nomeCompleto": "Agência 3937 - SONORA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Marcelo Miranda Soares, 920",
    "bairro": "Centro",
    "municipio": "Sonora",
    "uf": "MS",
    "cep": "79.415-000"
  },
  {
    "prefixo": "3950",
    "nome": "NOVA ALVORADA DO SUL",
    "nomeCompleto": "Agência 3950 - NOVA ALVORADA DO SUL",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Francisca Stradiotti, 1169",
    "bairro": "Centro",
    "municipio": "Nova Alvorada Do Sul",
    "uf": "MS",
    "cep": "79.140-000"
  },
  {
    "prefixo": "4336",
    "nome": "AV.WEIMAR TORRES",
    "nomeCompleto": "Agência 4336 - AV.WEIMAR TORRES",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Weimar Goncalves Torres, 2965",
    "bairro": "V.Lili",
    "municipio": "Dourados",
    "uf": "MS",
    "cep": "79.800-023"
  },
  {
    "prefixo": "4351",
    "nome": "JARDIM ALVORADA",
    "nomeCompleto": "Agência 4351 - JARDIM ALVORADA",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Jorge Elias Seba, 725",
    "bairro": "Jd.Alvorada",
    "municipio": "Tres Lagoas",
    "uf": "MS",
    "cep": "79.611-080"
  },
  {
    "prefixo": "4816",
    "nome": "RIBAS DO RIO PARDO",
    "nomeCompleto": "Agência 4816 - RIBAS DO RIO PARDO",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Aureliano Moura Brandao, 1200",
    "bairro": "Centro",
    "municipio": "Ribas Do Rio Pardo",
    "uf": "MS",
    "cep": "79.180-000"
  },
  {
    "prefixo": "5799",
    "nome": "MORENINHAS",
    "nomeCompleto": "Agência 5799 - MORENINHAS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Rua Fraiburgo, 1340",
    "bairro": "Vl C Morena",
    "municipio": "Campo Grande",
    "uf": "MS",
    "cep": "79.064-060"
  },
  {
    "prefixo": "6993",
    "nome": "JARDIM TIJUCA-MS",
    "nomeCompleto": "Agência 6993 - JARDIM TIJUCA-MS",
    "fonte": "Planilha agencias.xlsx",
    "endereco": "Avenida Marechal Deodoro, 2958",
    "bairro": "Jardim Tijuca",
    "municipio": "Campo Grande",
    "uf": "MS",
    "cep": "79.094-000"
  }
];
