(function (root) {
  'use strict';

  const CATALOG_VERSION = '2026.09.1';
  const source = (file, pages, note) => ({ file, pages, note });
  const unavailable = reason => ({ status: 'unavailable', engine: null, reason });
  const lines = [
    { id:'acl', name:'Antecipação a Clientes (ACL)', family:'Recebíveis', status:'informative', audience:'Empresas com recebíveis elegíveis', purpose:'Antecipação de valores a receber', terms:['Sujeita à análise cadastral, limite e qualidade dos recebíveis.'], sources:[source('estudo01.pdf','documento completo','Material de catálogo e contratação')], calculation:unavailable('Taxa, prazo e fluxo dependem das condições vigentes da contratação.') },
    { id:'limite-ouro', name:'Limite Ouro Empresarial', family:'Capital de giro', status:'informative', audience:'Pessoas jurídicas elegíveis', purpose:'Crédito rotativo para necessidades de curto prazo', terms:['Disponibilidade condicionada a limite vigente.'], sources:[source('estudo02.pdf','documento completo','Material de produto')], calculation:unavailable('Encargos e limites são parâmetros externos vigentes.') },
    { id:'desconto-titulos', name:'Desconto de Títulos Digital', family:'Recebíveis', status:'informative', audience:'Empresas com títulos elegíveis', purpose:'Antecipação de duplicatas e outros títulos aceitos', terms:['Elegibilidade depende do título, sacado e limite disponível.'], sources:[source('estudo03.pdf','documento completo','Material operacional e de produto')], calculation:unavailable('A precificação depende de parâmetros da operação.') },
    { id:'desconto-cheques', name:'Desconto de Cheques', family:'Recebíveis', status:'informative', audience:'Empresas com cheques elegíveis', purpose:'Antecipação de cheques pré-datados', terms:['Sujeito à análise dos cheques e do limite.'], sources:[source('estudo04.pdf','documento completo','Material de produto')], calculation:unavailable('A precificação depende de parâmetros da operação.') },
    { id:'conta-garantida', name:'Conta Garantida', family:'Capital de giro', status:'process', audience:'Pessoas jurídicas com limite contratado', purpose:'Cobertura de necessidades imediatas de caixa', terms:['O material disponível descreve o processo, não uma fórmula autônoma.'], sources:[source('estudo05.pdf','documento completo','Tutorial operacional')], calculation:unavailable('Fonte classificada como orientação de processo.') },
    { id:'bndes-digital', name:'BNDES Crédito Digital', family:'BNDES', status:'informative', audience:'Micro e pequenas empresas com faturamento anual de até R$ 4,8 milhões', purpose:'Capital de giro', terms:['Prazo documentado entre 13 e 24 meses.','Atividade rural não contemplada no material analisado.'], rules:[{field:'annualRevenue',operator:'lte',value:4800000,label:'Faturamento anual até R$ 4,8 milhões'}], sources:[source('estudo06.pdf','documento completo','Condições e fluxo digital')], calculation:unavailable('TFB Digital e demais parâmetros devem ser obtidos da fonte vigente.') },
    { id:'giro-digital', name:'Giro Digital', family:'Capital de giro', status:'process', audience:'Pessoas jurídicas elegíveis na plataforma', purpose:'Capital de giro', terms:['Fluxo de acolhimento e contratação digital.'], sources:[source('estudo07.pdf','documento completo','Orientação operacional')], calculation:unavailable('O documento analisado é predominantemente operacional.') },
    { id:'giro-empresa', name:'Giro Empresa', family:'Capital de giro', status:'process', audience:'Pessoas jurídicas elegíveis', purpose:'Capital de giro empresarial', terms:['Condições dependem do limite e da versão vigentes.'], sources:[source('estudo08.pdf','documento completo','Comunicado e processo')], calculation:unavailable('Material de versão/processo sem conjunto estável de parâmetros.') },
    { id:'bndes-giro', name:'BNDES Giro', family:'BNDES', status:'external_parameters', audience:'Empresas enquadradas nas políticas BNDES', purpose:'Capital de giro', terms:['Condições vinculadas às políticas e taxas BNDES vigentes.'], sources:[source('estudo09.pdf','documento completo','Condições BNDES e garantias')], calculation:unavailable('Taxas e parâmetros BNDES são externos e variáveis.') },
    { id:'pronampe-historico', name:'Pronampe — versão histórica', family:'Programas públicos', status:'historical', audience:'Micro e pequenas empresas conforme versão histórica', purpose:'Capital de giro e investimento', terms:['Registro histórico: até 50% da receita bruta anual anterior, limitado a R$ 180 mil.','Prazo histórico de até 48 meses, com até 6 de carência.'], sources:[source('estudo10.pdf','seção Pronampe anterior','Condições históricas')], calculation:unavailable('Versão preservada apenas para consulta histórica; não usar para contratação atual.') },
    { id:'pronampe-atual', name:'Pronampe — versão atual documentada', family:'Programas públicos', status:'external_parameters', audience:'Empresas enquadradas na regulamentação vigente', purpose:'Capital de giro e investimento', terms:['Referência documental: até 60% da receita bruta anual anterior, limitado a R$ 500 mil.','Prazo documentado de até 60 meses, com até 9 de carência.'], sources:[source('estudo10.pdf','seção Pronampe vigente','Condições da versão analisada')], calculation:unavailable('Selic e demais parâmetros precisam ser confirmados na data da proposta.') },
    { id:'procred-360', name:'ProCred 360', family:'Programas públicos', status:'external_parameters', audience:'Empresas enquadradas nas regras do programa', purpose:'Capital de giro e investimento', terms:['Referência documental: até 60% da receita bruta anual anterior, limitado a R$ 500 mil.','Prazo documentado de até 60 meses, com até 9 de carência.'], sources:[source('estudo10.pdf','seção ProCred 360','Condições da versão analisada')], calculation:unavailable('Parâmetros legais e financeiros exigem confirmação vigente.') },
    { id:'fies-empreendedor', name:'FIES Empreendedor', family:'Programas públicos', status:'external_parameters', audience:'Beneficiários elegíveis do FIES nas condições do programa', purpose:'Apoio ao empreendedor beneficiário', terms:['Valor máximo documentado de R$ 180 mil.','Taxa nominal indicada no material: 11,18% ao ano.'], sources:[source('estudo11.pdf','documento completo','Condições publicadas em 2026')], calculation:unavailable('Elegibilidade depende de bases e marcos temporais externos ao sistema.') },
    { id:'peac-fgi', name:'PEAC FGI', family:'Garantias', status:'informative', audience:'Empresas e grupos econômicos com receita bruta até R$ 300 milhões', purpose:'Garantia complementar para operações elegíveis', terms:['Não financia investimento fixo segundo o material analisado.','Sujeito a CNAEs e condições de enquadramento.'], rules:[{field:'annualRevenue',operator:'lte',value:300000000,label:'Receita bruta até R$ 300 milhões'}], sources:[source('estudo12.pdf','documento completo','Condições do programa')], calculation:unavailable('Cobertura e encargos dependem da operação e parâmetros vigentes.') },
    { id:'giro-cashback', name:'Giro Digital Cashback', family:'Capital de giro', status:'external_parameters', audience:'Pessoas jurídicas elegíveis, conforme FBA documentado', purpose:'Capital de giro com benefício condicionado', terms:['Benefício indicado de 0,10 ponto percentual, sujeito às regras vigentes.','Prazo total documentado de até 48 meses, incluindo até 3 de carência.'], rules:[{field:'annualRevenue',operator:'lte',value:5000000,label:'Faturamento anual até R$ 5 milhões'}], sources:[source('estudo13.pdf','documento completo','Taxa ponderada e cashback')], calculation:unavailable('A taxa-base e condições do benefício são parâmetros externos.') },
    { id:'aqt', name:'Aquisição de Títulos (AQT)', family:'Recebíveis', status:'informative', audience:'Empresas com recebíveis e sacados elegíveis', purpose:'Aquisição de direitos creditórios', terms:['Operação documentada sem exigência de garantias adicionais.','Risco pode considerar sacado e cedente.'], sources:[source('estudo14.pdf','documento completo','Condições e fluxo AQT')], calculation:unavailable('Preço depende do recebível, risco e condições da operação.') },
    { id:'aqs-cartao', name:'Aquisição de Saldos de Cartão (AQS)', family:'Recebíveis', status:'informative', audience:'Estabelecimentos com recebíveis de cartão elegíveis', purpose:'Antecipação de saldos de cartão', terms:['Usa o limite da adquirente conforme material analisado.','Não impacta o limite do cliente nas condições documentadas.'], sources:[source('estudo15.pdf','documento completo','Condições AQS')], calculation:unavailable('Preço e disponibilidade dependem da adquirente e da operação.') }
  ].map(line => Object.freeze({ catalogVersion:CATALOG_VERSION, rules:[], ...line }));

  const api = { CATALOG_VERSION, lines, getById:id => lines.find(line => line.id === id) || null };
  root.CentralCreditCatalog = api;
  if (typeof module === 'object' && module.exports) module.exports = api;
})(typeof window !== 'undefined' ? window : globalThis);
