(async function () {
  'use strict';
  const $ = id => document.getElementById(id), currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
  const SESSION_KEY = 'centralPipelineV1';
  const el = (tag, text, cls) => { const n = document.createElement(tag); if (text != null) n.textContent = text; if (cls) n.className = cls; return n; };
  const date = value => value ? value.split('-').reverse().join('/') : 'Não informado';
  const lines = value => [...new Set(String(value || '').split(/\r?\n/).map(v => v.trim()).filter(Boolean))];
  let db, model, workingModel, operations = [], view = 'columns', editingId = null;
  try { db = await CentralPipelineDb.open(); } catch (error) { $('pipelineEmpty').hidden = false; $('pipelineEmpty').querySelector('h2').textContent = 'SQLite indisponível'; $('pipelineEmpty').querySelector('p').textContent = error.message; return; }
  model = db.catalog(); operations = db.operations().map(CentralPipeline.normalizeOperation);
  let imported = null; try { imported = CentralPipeline.normalizePayload(JSON.parse(sessionStorage.getItem(SESSION_KEY) || 'null')); } catch (_) {}
  if (imported?.operations.length) { operations = CentralPipeline.mergeOperations(operations, imported.operations); await db.replaceOperations(operations); sessionStorage.removeItem(SESSION_KEY); }

  const category = id => model.categories.find(v => v.id === id), type = id => model.types.find(v => v.id === id), phase = id => model.phases.find(v => v.id === id), responsible = id => model.responsibles.find(v => v.id === id);
  const unique = key => [...new Set(operations.map(v => v[key]).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'pt-BR'));
  function refreshSelect(id, values, label) { const s = $(id), old = s.value; s.replaceChildren(); const empty = el('option', label); empty.value = ''; s.append(empty); values.forEach(v => { const o = el('option', v); o.value = v; s.append(o); }); s.value = values.includes(old) ? old : ''; }
  function filtered() { return CentralPipeline.filterOperations(operations, { query: $('pipelineSearch').value, stage: $('pipelineStage').value, responsible: $('pipelineResponsible').value }); }
  const editButton = id => { const b = el('button', 'Editar', 'pipeline-row-action'); b.type = 'button'; b.dataset.editOperation = id; return b; };
  function renderTable(items) { $('pipelineTableBody').replaceChildren(); items.forEach(op => { const tr = el('tr'); [op.proposal || '—', op.legalName || '—', op.mci || '—', op.originalType || '—', currency.format(op.amount)].forEach(v => tr.append(el('td', v))); const st = el('td'); st.append(el('span', op.originalStage, 'pipeline-stage')); tr.append(st); [op.responsibleLabel, date(op.enteredAt), date(op.deadline)].forEach(v => tr.append(el('td', v))); const a = el('td'); a.append(editButton(op.id)); tr.append(a); $('pipelineTableBody').append(tr); }); }
  function renderKanban(items) { $('kanbanView').replaceChildren(); for (const [stage, list] of CentralPipeline.groupByStage(items)) { const lane = el('section', null, 'pipeline-lane'), head = el('div', null, 'pipeline-lane__head'); head.append(el('h3', stage), el('span', list.length)); lane.append(head); list.forEach(op => { const card = el('article', null, 'pipeline-card'); card.append(el('h4', op.legalName || 'Cliente não informado'), el('p', `Proposta ${op.proposal || '—'} · MCI ${op.mci || '—'}`), el('p', op.originalType || 'Tipo não informado'), el('p', currency.format(op.amount), 'pipeline-card__amount')); const meta = el('div', null, 'pipeline-card__meta'); meta.append(el('span', op.responsibleLabel), el('span', date(op.enteredAt))); const edit = editButton(op.id); edit.className = 'pipeline-card__edit'; card.append(meta, edit); lane.append(card); }); $('kanbanView').append(lane); } }
  function render() { const has = operations.length > 0; $('pipelineEmpty').hidden = has; $('pipelineContent').hidden = !has; if (!has) return; refreshSelect('pipelineStage', unique('originalStage'), 'Todas as fases'); refreshSelect('pipelineResponsible', unique('responsibleLabel'), 'Todos os responsáveis'); const items = filtered(), m = CentralPipeline.summarize(items); $('pipelineSource').textContent = `${operations.length} ${operations.length === 1 ? 'operação salva' : 'operações salvas'} no SQLite deste navegador`; $('metricCount').textContent = m.count; $('metricAmount').textContent = currency.format(m.amount); $('metricStages').textContent = m.stages; $('metricResponsibles').textContent = m.responsibles; $('pipelineResultCount').textContent = `${items.length} de ${operations.length} ${operations.length === 1 ? 'operação' : 'operações'}`; renderTable(items); renderKanban(items); $('columnView').hidden = view !== 'columns'; $('kanbanView').hidden = view !== 'kanban'; $('viewColumns').setAttribute('aria-pressed', view === 'columns'); $('viewKanban').setAttribute('aria-pressed', view === 'kanban'); }

  function field(label, name, kind = 'text', value = '', required = false, options = []) { const w = el('label'); if (kind === 'textarea') w.dataset.wide = 'true'; const title = el('span', label + (required ? ' *' : '')); w.append(title); let c; if (kind === 'select') { c = el('select'); const p = el('option', 'Selecione'); p.value = ''; c.append(p); options.forEach(item => { const o = el('option', item.label); o.value = item.id; c.append(o); }); } else if (kind === 'textarea') c = el('textarea'); else { c = el('input'); c.type = kind; if (kind === 'number') { c.min = 0; c.step = '.01'; } } c.name = name; c.required = required; c.value = value ?? ''; w.append(c); return w; }
  function rebuildConditionalFields(op = {}) { const box = $('operationFields'), categoryId = box.querySelector('[name=categoryId]')?.value || op.categoryId || '', typeId = box.querySelector('[name=typeId]')?.value || op.typeId || ''; const preserved = Object.fromEntries([...box.querySelectorAll('[name]')].map(c => [c.name, c.value])); box.replaceChildren(); box.append(field('Categoria da operação', 'categoryId', 'select', categoryId, true, model.categories)); const types = model.types.filter(v => v.category_id === categoryId); box.append(field('Tipo da operação', 'typeId', 'select', typeId, true, types)); const phases = model.phases.filter(v => v.category_id === categoryId); box.append(field('Fase', 'phaseId', 'select', preserved.phaseId || op.phaseId, phases.length > 0, phases)); box.append(field('Número da proposta', 'proposal', 'text', preserved.proposal ?? op.proposal, true), field('Cliente ou razão social', 'legalName', 'text', preserved.legalName ?? op.legalName, true), field('MCI', 'mci', 'text', preserved.mci ?? op.mci), field('Valor da operação', 'amount', 'number', preserved.amount ?? op.amount, true), field('Responsável', 'responsibleId', 'select', preserved.responsibleId ?? op.responsibleId, false, model.responsibles), field('Data de entrada', 'enteredAt', 'date', preserved.enteredAt ?? op.enteredAt), field('Prazo', 'deadline', 'date', preserved.deadline ?? op.deadline)); const custom = model.fields.filter(v => v.category_id === categoryId && (!v.type_id || v.type_id === typeId)); const data = op.customData || {}; custom.forEach(f => box.append(field(f.label, `custom:${f.id}`, f.input_type === 'select' ? 'select' : f.input_type, preserved[`custom:${f.id}`] ?? data[f.id], f.required, (f.options || []).map(label => ({ id: label, label }))))); box.querySelector('[name=categoryId]').addEventListener('change', () => rebuildConditionalFields({ ...op, categoryId: box.querySelector('[name=categoryId]').value, typeId: '' })); box.querySelector('[name=typeId]').addEventListener('change', () => rebuildConditionalFields(op)); }
  function openOperation(op = null) { editingId = op?.id || null; $('operationDialogTitle').textContent = editingId ? 'Editar operação' : 'Nova operação'; $('operationMessage').textContent = ''; rebuildConditionalFields(op || {}); $('operationDialog').showModal(); }

  function renderWorkingModel() { const list = $('categoryConfigList'); list.replaceChildren(); workingModel.categories.forEach(cat => { const card = el('article', null, 'pipeline-category-card'); card.dataset.categoryId = cat.id; const head = el('div', null, 'pipeline-category-card__head'); const name = field('Categoria', 'categoryLabel', 'text', cat.label, true); const details = el('div'); details.style.display = 'grid'; details.style.gridTemplateColumns = '1fr 1fr'; details.style.gap = '10px'; const types = field('Tipos', 'categoryTypes', 'textarea', workingModel.types.filter(v => v.category_id === cat.id).map(v => v.label).join('\n')); const phases = field('Fases', 'categoryPhases', 'textarea', workingModel.phases.filter(v => v.category_id === cat.id).map(v => v.label).join('\n')); details.append(types, phases); const remove = el('button', 'Remover', 'pipeline-category-card__remove'); remove.type = 'button'; remove.dataset.removeCategory = cat.id; head.append(name, details, remove); card.append(head); list.append(card); }); const categorySelect = $('newFieldCategory'); categorySelect.replaceChildren(); workingModel.categories.forEach(cat => { const o = el('option', cat.label); o.value = cat.id; categorySelect.append(o); }); refreshFieldTypes(); renderCustomFields(); $('settingsResponsibles').value = workingModel.responsibles.map(v => v.name).join('\n'); }
  function refreshFieldTypes() { const selected = $('newFieldCategory').value, select = $('newFieldType'); select.replaceChildren(); const all = el('option', 'Todos os tipos'); all.value = ''; select.append(all); workingModel.types.filter(v => v.category_id === selected).forEach(v => { const o = el('option', v.label); o.value = v.id; select.append(o); }); }
  function renderCustomFields() { const list = $('customFieldList'); list.replaceChildren(); workingModel.fields.forEach(f => { const row = el('div', null, 'pipeline-custom-field'), info = el('div'); info.append(el('strong', f.label), el('span', `${f.input_type}${f.required ? ' · obrigatório' : ''}`)); const scope = el('div', `${workingModel.categories.find(v => v.id === f.category_id)?.label || ''}${f.type_id ? ' · ' + (workingModel.types.find(v => v.id === f.type_id)?.label || '') : ' · todos os tipos'}`, 'pipeline-custom-field__scope'); const remove = el('button', 'Remover', 'pipeline-custom-field__remove'); remove.type = 'button'; remove.dataset.removeField = f.id; row.append(info, scope, remove); list.append(row); }); }
  function openSettings() { workingModel = structuredClone(model); $('settingsMessage').textContent = ''; renderWorkingModel(); $('settingsDialog').showModal(); }
  function collectCategories() { const categories = [], types = [], phases = []; document.querySelectorAll('[data-category-id]').forEach((card, index) => { const id = card.dataset.categoryId, label = card.querySelector('[name=categoryLabel]').value.trim(); if (!label) return; categories.push({ id, label }); lines(card.querySelector('[name=categoryTypes]').value).forEach(v => types.push({ id: `${id}-${CentralPipelineDb.slug(v)}`, category_id: id, label: v })); lines(card.querySelector('[name=categoryPhases]').value).forEach(v => phases.push({ id: `${id}-${CentralPipelineDb.slug(v)}`, category_id: id, label: v })); }); workingModel.categories = categories; workingModel.types = types; workingModel.phases = phases; }

  $('operationForm').addEventListener('submit', async event => { event.preventDefault(); if (!event.currentTarget.reportValidity()) return; const data = new FormData(event.currentTarget), cat = category(data.get('categoryId')), typ = type(data.get('typeId')), ph = phase(data.get('phaseId')), resp = responsible(data.get('responsibleId')), existing = operations.find(v => v.id === editingId); const customData = {}; for (const [key, value] of data) if (key.startsWith('custom:')) customData[key.slice(7)] = value; const draft = { ...(existing || {}), id: existing?.id || `manual-${Date.now()}`, categoryId: cat?.id || '', typeId: typ?.id || '', phaseId: ph?.id || '', responsibleId: resp?.id || '', proposal: data.get('proposal'), legalName: data.get('legalName'), mci: data.get('mci'), amount: data.get('amount'), enteredAt: data.get('enteredAt'), deadline: data.get('deadline'), originalType: typ?.label || '', originalStage: ph?.label || 'Sem fase informada', responsibleLabel: resp?.name || 'Não informado', customData, origin: existing?.origin || 'Manual' }; const normalized = CentralPipeline.normalizeOperation(draft); Object.assign(normalized, { categoryId: draft.categoryId, typeId: draft.typeId, phaseId: draft.phaseId, responsibleId: draft.responsibleId, customData }); operations = existing ? operations.map(v => v.id === existing.id ? normalized : v) : [...operations, normalized]; await db.replaceOperations(operations); $('operationDialog').close(); render(); });
  $('settingsForm').addEventListener('submit', async event => { event.preventDefault(); collectCategories(); if (!workingModel.categories.length) { $('settingsMessage').textContent = 'Cadastre ao menos uma categoria.'; return; } workingModel.responsibles = lines($('settingsResponsibles').value).map(name => ({ id: CentralPipelineDb.slug(name), name })); await db.replaceCatalog(workingModel); model = db.catalog(); $('settingsDialog').close(); render(); });
  $('addPipelineCategory').addEventListener('click', () => { collectCategories(); const label = $('newCategoryName').value.trim(); if (!label) return; const id = CentralPipelineDb.slug(label); if (!workingModel.categories.some(v => v.id === id)) workingModel.categories.push({ id, label }); $('newCategoryName').value = ''; renderWorkingModel(); });
  $('newFieldCategory').addEventListener('change', refreshFieldTypes); $('newFieldInputType').addEventListener('change', () => $('newFieldOptionsWrap').hidden = $('newFieldInputType').value !== 'select');
  $('addPipelineField').addEventListener('click', () => { collectCategories(); const label = $('newFieldLabel').value.trim(), categoryId = $('newFieldCategory').value; if (!label || !categoryId) return; workingModel.fields.push({ id: `${categoryId}-${CentralPipelineDb.slug(label)}-${Date.now()}`, category_id: categoryId, type_id: $('newFieldType').value || null, label, input_type: $('newFieldInputType').value, required: $('newFieldRequired').checked, options: lines($('newFieldOptions').value) }); $('newFieldLabel').value = ''; $('newFieldOptions').value = ''; renderWorkingModel(); });
  document.addEventListener('click', event => { if (event.target.closest('[data-new-operation]')) return openOperation(); if (event.target.closest('[data-open-settings]')) return openSettings(); const edit = event.target.closest('[data-edit-operation]'); if (edit) return openOperation(operations.find(v => v.id === edit.dataset.editOperation)); const close = event.target.closest('[data-close-dialog]'); if (close) return $(close.dataset.closeDialog).close(); const removeCat = event.target.closest('[data-remove-category]'); if (removeCat) { workingModel.categories = workingModel.categories.filter(v => v.id !== removeCat.dataset.removeCategory); workingModel.types = workingModel.types.filter(v => v.category_id !== removeCat.dataset.removeCategory); workingModel.phases = workingModel.phases.filter(v => v.category_id !== removeCat.dataset.removeCategory); workingModel.fields = workingModel.fields.filter(v => v.category_id !== removeCat.dataset.removeCategory); renderWorkingModel(); } const removeField = event.target.closest('[data-remove-field]'); if (removeField) { workingModel.fields = workingModel.fields.filter(v => v.id !== removeField.dataset.removeField); renderCustomFields(); } });
  $('restorePipelineSettings').addEventListener('click', () => { workingModel = { categories: [{ id: 'investimento', label: 'Investimento' }, { id: 'giro', label: 'Giro' }, { id: 'aditivo', label: 'Aditivo' }], types: ['FCO Turismo', 'FCO Rural', 'FCO Serviços', 'FCO Infraestrutura', 'Investimento PJ'].map(label => ({ id: `investimento-${CentralPipelineDb.slug(label)}`, category_id: 'investimento', label })), phases: [], fields: [], responsibles: [] }; renderWorkingModel(); });
  $('viewColumns').onclick = () => { view = 'columns'; render(); }; $('viewKanban').onclick = () => { view = 'kanban'; render(); }; ['pipelineSearch', 'pipelineStage', 'pipelineResponsible'].forEach(id => $(id).addEventListener(id === 'pipelineSearch' ? 'input' : 'change', render)); $('clearPipelineFilters').onclick = () => { $('pipelineSearch').value = $('pipelineStage').value = $('pipelineResponsible').value = ''; render(); }; render();
})();
